import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "../globals.css";
import Layout from "@/layout/layout";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const figtree = Figtree({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className={`${figtree.className} flex flex-col `}>
        <Toaster
          richColors
          position="top-center"
          toastOptions={{
            classNames: {
              toast: "bg-zinc-900 text-white border border-zinc-700",
              title: "text-white",
              description: "text-zinc-400",
            },
          }}
        />

        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
